<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Testing Start</title>
    <style>
        body {
            background-color: #faf0e6;
            margin: auto;
        }
    </style>

</head>

<body>
<div align="center">
    <h2 style="color: #8686c8">Тест студента  ${student.name}  ${student.surName}</h2>
    <br>
    <br>
    <br>

    <div>

        <b>
            <a href="/passTest/${student.id}"><h3>Старт теста</h3></a>
        </b>

    </div>

</div>

</body>
</html>